# Generated by Django 3.2 on 2023-09-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230905_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='user',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='author',
            new_name='following',
        ),
    ]
