# Generated by Django 3.2 on 2023-09-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230831_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.SmallIntegerField(max_length=200, null=True, verbose_name='Количество ингредиентов'),
        ),
    ]
