# Generated by Django 3.2 on 2023-09-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_ingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.SmallIntegerField(null=True, verbose_name='Количество ингредиентов'),
        ),
    ]
