# Generated by Django 3.2 on 2023-09-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20230904_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.AddField(
            model_name='recipe',
            name='amount',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Количество ингредиента'),
        ),
    ]
