# Generated by Django 3.2 on 2023-09-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20230908_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='Тег'),
            preserve_default=False,
        ),
    ]
