# Generated by Django 3.2 on 2023-09-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='measurement_unit',
            field=models.CharField(default=1, max_length=200, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
    ]
