# Generated by Django 3.2 on 2023-09-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_recipe_measurement_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientrecipe',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='measurement_unit',
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='measurement_unit',
            field=models.CharField(default=1, max_length=200, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
    ]
