# Generated by Django 3.2 on 2023-09-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_auto_20230908_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientrecipe',
            name='measurement_unit',
        ),
    ]
