# Generated by Django 3.2 on 2023-09-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_remove_ingredientrecipe_measurement_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecipe',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Ингредиент'),
        ),
    ]
