# Generated by Django 3.2 on 2023-09-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_ingredientrecipe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientrecipe',
            name='name',
        ),
    ]
