# Generated by Django 3.2 on 2023-09-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_auto_20230908_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Количество ингредиента'),
        ),
    ]
